### ISSUE TITLE
O(n*log(n)) fast

### ISSUE THREAD

**Issue by jasonnicholson** [robince/stockwelltransform#1]
Is this the O(n*log(n)) algorithm?

**Comment by robince** [comment]
Sorry I completely missed these issues at the time. 
No, this is the "full" oversampled version (I use it for data visualisation etc.). 
I have the fast one (output same number of data points as the input) in a different repository. Again was an existing package I just made tweaks to (Matlab wrapper, and a different overlapping partitioning scheme for real signals):
https://github.com/robince/fst-uofc
