### ISSUE TITLE
Request for an Example

### ISSUE THREAD

**Issue by jasonnicholson** [robince/stockwelltransform#2]
A little more Doucmentation would be helpful. I am looking for an example of how to use the S-transform: https://github.com/claudiodsf/stockwell/blob/master/README.md

MinGW-W64 and FFTW3 setup was required on the way to compiling this function:

1. Setup MinGW-w64. I recommend using the Add-on in MATLAB because this references the version of MinGW-w64 is compatible with the version of MATLAB installed.
![image](https://user-images.githubusercontent.com/1058191/100523814-f9b29900-3178-11eb-8bb1-afce9bf18745.png)
![image](https://user-images.githubusercontent.com/1058191/100523830-177ffe00-3179-11eb-8c6a-26887cdabbba.png)
2. Add the MinGW-w64 bin directory to the Windows path. Mine is located here: C:\ProgramData\MATLAB\SupportPackages\R2020b\3P.instrset\mingw_w64.instrset\bin . We need this because we need to use dlltool.exe in later steps.
3.  Get the fftw3 binaries for windows from [here](http://www.fftw.org/download.html). Save it somewhere like C:\fftw3 or C:\Users\username\fftw3.
4. From a command prompt in the fftw3 folder, use dlltool.exe to generate a .lib that can be used later compilation steps:
` dlltool -d libfftw3-3.def -l libfftw3-3.lib`
5. In MATLAB, the library needs to be compiled:
```
mex -v -c st_src.c -IC:\fftw3
mex -v st.c st_src.obj -LC:\fftw3 -llibfftw3-3.lib
```

The general MATLAB user isn't going to get through the compiling steps. Maybe, polishing them up a little would help.

Good luck. Thanks for reading.

**Comment by robince** [comment]
Thanks for this - I had actually never got it to work on Windows. I wasn't able to get a working mex file with MinGW but I've updated with some more detailed instructions for compiling with Visual Studio Community Edition. I had to make some small fixes to support windows.
